# Chapter 2 Extending Python Using NumPy

## Creating NumPy Arrays

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
a2 = np.arange(0, 10, 2)
print(a2)

[0 2 4 6 8]


In [4]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [5]:
a4 = np.zeros((2, 3))
print(a4.shape)
print(a4)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
a5 = np.full((2, 3), 8)
print(a5)

[[8 8 8]
 [8 8 8]]


In [7]:
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
a7 = np.random.random((2, 4))
print(a7)

[[0.76548216 0.50462346 0.91790841 0.0147618 ]
 [0.77832908 0.77936299 0.70441256 0.02943091]]


In [9]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1)

[1 2 3 4 5]


## Array Indexing

In [10]:
print(r1[0])
print(r1[1])

1
2


In [11]:
list2 = [6, 7, 8, 9, 0]
r2 = np.array([list1, list2])
print(r2)
print(r2.shape)
print(r2[0, 0])
print(r2[0, 1])
print(r2[1, 0])

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
1
2
6


In [12]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1[[2, 4]])

[3 5]
