# Chapter 2 Extending Python Using NumPy

## Creating NumPy Arrays

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
a2 = np.arange(0, 10, 2)
print(a2)

[0 2 4 6 8]


In [4]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [5]:
a4 = np.zeros((2, 3))
print(a4.shape)
print(a4)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
a5 = np.full((2, 3), 8)
print(a5)

[[8 8 8]
 [8 8 8]]


In [7]:
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
a7 = np.random.random((2, 4))
print(a7)

[[0.1504593  0.45413363 0.16985921 0.2230918 ]
 [0.22394885 0.96584778 0.63245018 0.29145393]]


In [9]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1)

[1 2 3 4 5]


## Array Indexing

In [10]:
print(r1[0])
print(r1[1])

1
2


In [11]:
list2 = [6, 7, 8, 9, 0]
r2 = np.array([list1, list2])
print(r2)
print(r2.shape)
print(r2[0, 0])
print(r2[0, 1])
print(r2[1, 0])

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
1
2
6


In [12]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1[[2, 4]])

[3 5]


### Boolean Indexing

In [13]:
print(r1 > 2)

[False False  True  True  True]


In [14]:
print(r1[r1 > 2])

[3 4 5]


In [15]:
nums = np.arange(20)
print(nums)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
odd_num = nums[nums % 2 == 1]
print(odd_num)

[ 1  3  5  7  9 11 13 15 17 19]


### Slicing Arrays

In [17]:
a = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [9, 8, 7, 6, 5]])
print(a)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


In [18]:
b1 = a[1:3, :3]
print(b1)

[[4 5 6]
 [9 8 7]]


In [19]:
b2 = a[-2:, -2:]
print(b2)

[[7 8]
 [6 5]]


### NumPy Slice Is a Reference

In [20]:
b3 = a[1:, 2:]
print(b3)

[[6 7 8]
 [7 6 5]]


In [21]:
b3[0, 2] = 88
print(a)

[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]


In [22]:
b4 = a[2:, :]
print(b4)
print(b4.shape)

[[9 8 7 6 5]]
(1, 5)


In [23]:
b5 = a[2, :]
print(b5)

[9 8 7 6 5]


In [24]:
print(b5.shape)

(5,)


## Reshaping Array

In [25]:
b5 = b5.reshape(1, -1)
print(b5)

[[9 8 7 6 5]]


In [26]:
b4.reshape(-1, )

array([9, 8, 7, 6, 5])

## Array Math

In [27]:
x1 = np.array([[1, 2, 3], [4, 5, 6]])
y1 = np.array([[7, 8, 9], [2, 3, 4]])

In [28]:
print(x1 + y1)

[[ 8 10 12]
 [ 6  8 10]]


In [29]:
x = np.array([2, 3])
y = np.array([4, 2])
z = x + y
z

array([6, 5])

In [30]:
np.add(x1, y1)

array([[ 8, 10, 12],
       [ 6,  8, 10]])

In [31]:
print(x1 - y1)  # same as np.subtract(x1,y1)

[[-6 -6 -6]
 [ 2  2  2]]


In [32]:
print(x1 * y1)  # same as np.multiply(x1,y1)

[[ 7 16 27]
 [ 8 15 24]]


In [33]:
print(x1 / y1)  # same as np.divide(x1,y1)

[[0.14285714 0.25       0.33333333]
 [2.         1.66666667 1.5       ]]


In [34]:
names = np.array(['Ann', 'Joe', 'Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

In [35]:
bmi = weights / heights ** 2  # calculate the BMI
print(bmi)  # [ 28.88888889  14.51836889  23.046875  ]

[28.88888889 14.51836889 23.046875  ]


In [36]:
print("Overweight: ", names[bmi > 25])
# Overweight:  ['Ann']

Overweight:  ['Ann']


In [37]:
print("Underweight: ", names[bmi < 18.5])
# Underweight:  ['Joe']

Underweight:  ['Joe']


In [38]:
print("Healthy: ", names[(bmi >= 18.5) & (bmi <= 25)])
# Healthy:  ['Mark']

Healthy:  ['Mark']


### Dot Product

In [39]:
x = np.array([2, 3])
y = np.array([4, 2])
np.dot(x, y)

14

In [40]:
x2 = np.array([[1, 2, 3], [4, 5, 6]])
y2 = np.array([[7, 8], [9, 10], [11, 12]])
print(np.dot(x2, y2))

[[ 58  64]
 [139 154]]


### Matrix

In [41]:
x2 = np.matrix([[1, 2], [4, 5]])
y2 = np.matrix([[7, 8], [2, 3]])

In [42]:
x1 = np.array([[1, 2], [4, 5]])
y1 = np.array([[7, 8], [2, 3]])
x1 = np.asmatrix(x1)
y1 = np.asmatrix(y1)

In [43]:
x1 = np.array([[1, 2], [4, 5]])
y1 = np.array([[7, 8], [2, 3]])
print(x1 * y1)

[[ 7 16]
 [ 8 15]]


In [44]:
x2 = np.matrix([[1, 2], [4, 5]])
y2 = np.matrix([[7, 8], [2, 3]])
print(x2 * y2)

[[11 14]
 [38 47]]


### Cumulative Sum

In [45]:
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
print(a.cumsum())

[ 1  3  6 10 15 21 28 36 45]


In [47]:
print(a.cumsum(axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [48]:
print(a.cumsum(axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


### NumPy Sorting

In [49]:
ages = np.array([34, 12, 37, 5, 13])
sorted_ages = np.sort(ages)
print(sorted_ages)
print(ages)

[ 5 12 13 34 37]
[34 12 37  5 13]


In [50]:
ages.sort()
print(ages)

[ 5 12 13 34 37]


In [51]:
ages = np.array([34, 12, 37, 5, 13])
print(ages.argsort())

[3 1 4 0 2]


In [52]:
print(ages[ages.argsort()])

[ 5 12 13 34 37]


In [53]:
persons = np.array(['Johnny', 'Mary', 'Peter', 'Will', 'Joe'])
ages = np.array([34, 12, 37, 5, 13])
heights = np.array([1.76, 1.2, 1.68, 0.5, 1.25])

In [54]:
sort_indices = np.argsort(ages)

In [55]:
print(persons[sort_indices])
print(ages[sort_indices])
print(heights[sort_indices])

['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
[ 5 12 13 34 37]
[0.5  1.2  1.25 1.76 1.68]


In [56]:
sort_indices = np.argsort(persons)
print(persons[sort_indices])
print(ages[sort_indices])
print(heights[sort_indices])

['Joe' 'Johnny' 'Mary' 'Peter' 'Will']
[13 34 12 37  5]
[1.25 1.76 1.2  1.68 0.5 ]


In [57]:
reverse_sort_indices = np.argsort(persons)[::-1]
print(persons[reverse_sort_indices])
print(ages[reverse_sort_indices])
print(heights[reverse_sort_indices])

['Will' 'Peter' 'Mary' 'Johnny' 'Joe']
[ 5 37 12 34 13]
[0.5  1.68 1.2  1.76 1.25]


## Array Assignment

### Copying by Reference

In [58]:
list1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
a1 = np.array(list1)
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [59]:
a2 = a1
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [60]:
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [61]:
a2[0][0] = 11
print(a1)

[[11  2  3  4]
 [ 5  6  7  8]]


In [62]:
print(a2)

[[11  2  3  4]
 [ 5  6  7  8]]


In [63]:
a1.shape = 1, -1
print(a1)

[[11  2  3  4  5  6  7  8]]


In [64]:
print(a2)

[[11  2  3  4  5  6  7  8]]
