# Chapter 2 Extending Python Using NumPy

## Creating NumPy Arrays

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
a2 = np.arange(0, 10, 2)
print(a2)

[0 2 4 6 8]


In [4]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [5]:
a4 = np.zeros((2, 3))
print(a4.shape)
print(a4)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
a5 = np.full((2, 3), 8)
print(a5)

[[8 8 8]
 [8 8 8]]


In [7]:
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
a7 = np.random.random((2, 4))
print(a7)

[[0.62378957 0.33628757 0.5811447  0.70379256]
 [0.40158184 0.46156076 0.32922    0.17063592]]


In [9]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1)

[1 2 3 4 5]


## Array Indexing

In [10]:
print(r1[0])
print(r1[1])

1
2


In [11]:
list2 = [6, 7, 8, 9, 0]
r2 = np.array([list1, list2])
print(r2)
print(r2.shape)
print(r2[0, 0])
print(r2[0, 1])
print(r2[1, 0])

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
1
2
6


In [12]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1[[2, 4]])

[3 5]


### Boolean Indexing

In [13]:
print(r1 > 2)

[False False  True  True  True]


In [14]:
print(r1[r1 > 2])

[3 4 5]


In [15]:
nums = np.arange(20)
print(nums)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
odd_num = nums[nums % 2 == 1]
print(odd_num)

[ 1  3  5  7  9 11 13 15 17 19]


### Slicing Arrays

In [17]:
a = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [9, 8, 7, 6, 5]])
print(a)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


In [18]:
b1 = a[1:3, :3]
print(b1)

[[4 5 6]
 [9 8 7]]


In [19]:
b2 = a[-2:, -2:]
print(b2)

[[7 8]
 [6 5]]


### NumPy Slice Is a Reference

In [20]:
b3 = a[1:, 2:]
print(b3)

[[6 7 8]
 [7 6 5]]


In [21]:
b3[0, 2] = 88
print(a)

[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]


In [22]:
b4 = a[2:, :]
print(b4)
print(b4.shape)

[[9 8 7 6 5]]
(1, 5)


In [23]:
b5 = a[2, :]
print(b5)

[9 8 7 6 5]


In [24]:
print(b5.shape)

(5,)


## Reshaping Array

In [25]:
b5 = b5.reshape(1, -1)
print(b5)

[[9 8 7 6 5]]


In [26]:
b4.reshape(-1,)

array([9, 8, 7, 6, 5])

## Array Math

In [27]:
x1 = np.array([[1, 2, 3], [4, 5, 6]])
y1 = np.array([[7, 8, 9], [2, 3, 4]])

In [28]:
print(x1 + y1)

[[ 8 10 12]
 [ 6  8 10]]


In [29]:
x = np.array([2, 3])
y = np.array([4, 2])
z = x + y
z

array([6, 5])

In [30]:
np.add(x1, y1)

array([[ 8, 10, 12],
       [ 6,  8, 10]])

In [31]:
print(x1 - y1)     # same as np.subtract(x1,y1)

[[-6 -6 -6]
 [ 2  2  2]]


In [32]:
print(x1 * y1)     # same as np.multiply(x1,y1)

[[ 7 16 27]
 [ 8 15 24]]


In [33]:
print(x1 / y1)     # same as np.divide(x1,y1)

[[0.14285714 0.25       0.33333333]
 [2.         1.66666667 1.5       ]]


In [34]:
names = np.array(['Ann', 'Joe', 'Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

In [35]:
bmi = weights / heights**2            # calculate the BMI
print(bmi)                           # [ 28.88888889  14.51836889  23.046875  ]

[28.88888889 14.51836889 23.046875  ]


In [36]:
print("Overweight: ", names[bmi > 25])
# Overweight:  ['Ann']

Overweight:  ['Ann']


In [37]:
print("Underweight: ", names[bmi < 18.5])
# Underweight:  ['Joe']

Underweight:  ['Joe']


In [38]:
print("Healthy: ", names[(bmi >= 18.5) & (bmi <= 25)])
# Healthy:  ['Mark']

Healthy:  ['Mark']


### Dot Product

In [39]:
x = np.array([2, 3])
y = np.array([4, 2])
np.dot(x, y)

14

In [40]:
x2 = np.array([[1, 2, 3], [4, 5, 6]])
y2 = np.array([[7, 8], [9, 10], [11, 12]])
print(np.dot(x2, y2))

[[ 58  64]
 [139 154]]
