# Chapter 2 Extending Python Using NumPy

## Creating NumPy Arrays

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
a2 = np.arange(0, 10, 2)
print(a2)

[0 2 4 6 8]


In [4]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [5]:
a4 = np.zeros((2, 3))
print(a4.shape)
print(a4)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
a5 = np.full((2, 3), 8)
print(a5)

[[8 8 8]
 [8 8 8]]


In [7]:
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
a7 = np.random.random((2, 4))
print(a7)

[[0.00656757 0.56246    0.67616198 0.44527216]
 [0.69538776 0.55772033 0.52261329 0.63663724]]


In [9]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1)

[1 2 3 4 5]
